version: '3'
services:
  db01:
    image: mongo:3.2
    volumes:
    - datadb01:/data/db
    - ./etc/mongodb.conf:/etc/mongodb.conf
    ports:
    - "27017:27017"
    command: ["mongod", "--config", "/etc/mongodb.conf"]
    container_name: db01

volumes:
  datadb01:
